import { budgetRemaining, categoryRollups, fixedVariableTotals, formatMoney, hourlyGross, netWorth, parseMoney, paycheckEstimate, reconciledPay, retirementProjection, savingsProjection, savingsRate } from './calculations.js';
import { mountEcosystemProfileMenu } from '../shared/identity.js?v=3';

const SETTINGS_KEY='money-settings-v1';
const THEMES=['classic','ledger','clear','vault','market'];
const DEFAULT_SETTINGS={theme:'classic',density:'comfortable',onboardingDismissed:false};
const NAV_GROUPS={overview:['overview'],budget:['budget','transactions','bills'],plan:['savings','retirement'],more:['earnings','assets','reports']};
const NAV_LABELS={budget:'Monthly plan',transactions:'Transactions',bills:'Bills',savings:'Savings',retirement:'Retirement',earnings:'Earnings',assets:'Assets & net worth',reports:'Reports'};
const TABLES={categories:'money_categories',budgets:'money_monthly_budgets',assets:'money_assets',incomeSources:'money_income_sources',workEntries:'money_work_entries',paychecks:'money_paychecks',transactions:'money_transactions',bills:'money_bills',savingsGoals:'money_savings_goals',contributions:'money_savings_contributions',retirementProfiles:'money_retirement_profiles',retirementAccounts:'money_retirement_accounts',allocations:'money_investment_allocations',snapshots:'money_net_worth_snapshots'};
const client=window.AppAuth?.client||null;
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
let currentUser=null,settings=loadSettings(),activeView='overview',onboardingStep=1;
let state=Object.fromEntries(Object.keys(TABLES).map((key)=>[key,[]]));
let loadedUserId=null,sessionLoadPromise=null;

initialize();

async function initialize(){
  applySettings();enhanceRetirementDisclosure();bindEvents();setDefaultDates();updateIncomeSourceExperience();updateOnboardingFields();
  if(!client)return redirectToLogin();
  client.auth.onAuthStateChange((_event,session)=>setTimeout(()=>applySession(session),0));
  const{data,error}=await client.auth.getSession();if(error||!data.session)return redirectToLogin();await applySession(data.session);
}

async function applySession(session){
  if(!session?.user?.email_confirmed_at){if(session?.user)await client.auth.signOut();return redirectToLogin()}
  if(loadedUserId===session.user.id)return;
  if(sessionLoadPromise)return sessionLoadPromise;
  currentUser=session.user;setCloud('Loading private records…');void mountEcosystemProfileMenu({client,user:currentUser,appId:'money',onSettings:openSettings,onSignOut:()=>client.auth.signOut()});
  sessionLoadPromise=(async()=>{try{await loadState();if(!state.categories.length)await seedCategories();loadedUserId=currentUser.id;document.body.classList.remove('auth-pending');setCloud('Cloud verified');hideLoadNotice();populateControls();applyRoute();renderAll();maybeOpenOnboarding()}
  catch(error){loadedUserId=null;document.body.classList.remove('auth-pending');setCloud('Cloud load failed',true);showLoadError(error)}})();
  try{await sessionLoadPromise}finally{sessionLoadPromise=null}
}

function redirectToLogin(){location.replace(`${location.origin}/account/?returnTo=/money/`)}
async function loadState(){const results=await Promise.all(Object.values(TABLES).map((table)=>client.from(table).select('*')));const error=results.find((item)=>item.error)?.error;if(error)throw error;Object.keys(TABLES).forEach((key,index)=>{state[key]=results[index].data||[]})}
async function saveRow(key,row){const record={...row,user_id:currentUser.id};const{data,error}=await client.from(TABLES[key]).upsert(record,{onConflict:'user_id,id'}).select().single();if(error)throw error;const index=state[key].findIndex((item)=>item.id===data.id);if(index>=0)state[key][index]=data;else state[key].push(data);return data}
async function removeRow(key,id){const{error}=await client.from(TABLES[key]).delete().eq('user_id',currentUser.id).eq('id',id);if(error)throw error;state[key]=state[key].filter((item)=>item.id!==id)}

async function seedCategories(){
  const food=crypto.randomUUID(),transport=crypto.randomUUID(),housing=crypto.randomUUID(),income=crypto.randomUUID();
  const rows=[
    {id:food,name:'Food',parent_id:null,category_type:'expense',classification:'variable',sort_order:10},{id:crypto.randomUUID(),name:'Groceries',parent_id:food,category_type:'expense',classification:null,sort_order:11},{id:crypto.randomUUID(),name:'Restaurants',parent_id:food,category_type:'expense',classification:null,sort_order:12},{id:crypto.randomUUID(),name:'Coffee',parent_id:food,category_type:'expense',classification:null,sort_order:13},
    {id:transport,name:'Transportation',parent_id:null,category_type:'expense',classification:'variable',sort_order:20},{id:crypto.randomUUID(),name:'Gas',parent_id:transport,category_type:'expense',classification:null,sort_order:21},{id:crypto.randomUUID(),name:'Maintenance',parent_id:transport,category_type:'expense',classification:null,sort_order:22},{id:crypto.randomUUID(),name:'Parking',parent_id:transport,category_type:'expense',classification:null,sort_order:23},
    {id:housing,name:'Housing',parent_id:null,category_type:'expense',classification:'fixed',sort_order:30},{id:crypto.randomUUID(),name:'Rent / Mortgage',parent_id:housing,category_type:'expense',classification:null,sort_order:31},{id:crypto.randomUUID(),name:'Utilities',parent_id:housing,category_type:'expense',classification:null,sort_order:32},
    {id:income,name:'Pay & Earnings',parent_id:null,category_type:'income',classification:null,sort_order:100}
  ].map((row)=>({...row,user_id:currentUser.id,active:true}));
  const{data,error}=await client.from(TABLES.categories).insert(rows).select();if(error)throw error;state.categories=data;
}

function bindEvents(){
  $$('[data-view-target]').forEach((button)=>button.addEventListener('click',()=>showView(button.dataset.viewTarget)));
  $$('[data-quick]').forEach((button)=>button.addEventListener('click',()=>runQuickAction(button.dataset.quick)));
  window.addEventListener('hashchange',applyRoute);
  $('#closeSettings').addEventListener('click',()=>$('#settingsModal').close());
  $$('[data-settings-open]').forEach((button)=>button.addEventListener('click',()=>showSettingsPanel(button.dataset.settingsOpen)));$$('[data-settings-back]').forEach((button)=>button.addEventListener('click',()=>showSettingsPanel('main')));
  $('#settingsModal').addEventListener('close',()=>showSettingsPanel('main',false));$('#settingsModal').addEventListener('change',saveSettingsControls);$('#signOut').addEventListener('click',()=>client.auth.signOut());$('#resetMoney').addEventListener('click',resetMoney);
  $('#retryLoad').addEventListener('click',()=>applySession(currentUser?{user:currentUser}:null));
  $('#overviewMonth').addEventListener('change',renderOverview);$('#budgetMonth').addEventListener('change',async()=>{await ensureBudgetMonth($('#budgetMonth').value);renderBudget()});
  $('#categoryForm').addEventListener('submit',saveCategory);$('#categoryForm').addEventListener('reset',()=>setTimeout(()=>{$('#categoryId').value=''},0));
  $('#transactionForm').addEventListener('submit',saveTransaction);$('#transactionForm').addEventListener('reset',()=>setTimeout(()=>{$('#transactionId').value=''},0));['transactionSearch','transactionFilter','transactionSort'].forEach((id)=>$(`#${id}`).addEventListener('input',renderTransactions));
  $('#billForm').addEventListener('submit',saveBill);$('#billForm').addEventListener('reset',()=>setTimeout(()=>{$('#billId').value='';$('#billActive').checked=true},0));
  $('#incomeSourceForm').addEventListener('submit',saveIncomeSource);['incomeSourceType','incomeHourlyRate','incomeExpectedHours','incomeSalary','incomeFrequency'].forEach((id)=>$(`#${id}`).addEventListener('input',updateIncomeSourceExperience));$('#workForm').addEventListener('submit',saveWork);$('#paycheckForm').addEventListener('submit',savePaycheck);['workSource','workRegular','workOvertime'].forEach((id)=>$(`#${id}`).addEventListener('input',updateWorkEstimate));['payGross','payPreTax','payRetirement','payBenefits','payFederalRate','payStateRate','payPostTax'].forEach((id)=>$(`#${id}`).addEventListener('input',updatePayEstimate));
  $('#savingsForm').addEventListener('submit',saveSavingsGoal);$('#contributionForm').addEventListener('submit',saveContribution);$('#retirementForm').addEventListener('submit',saveRetirementProfile);$('#retirementAccountForm').addEventListener('submit',saveRetirementAccount);$('#allocationForm').addEventListener('submit',saveAllocation);$$('[data-ret-scenario]').forEach((button)=>button.addEventListener('click',()=>applyRetirementScenario(button.dataset.retScenario)));
  $('#assetForm').addEventListener('submit',saveAsset);$('#snapshotNetWorth').addEventListener('click',saveNetWorthSnapshot);$('#reportRange').addEventListener('change',renderReports);['reportStart','reportEnd'].forEach(id=>$(`#${id}`).addEventListener('change',renderReports));
  document.addEventListener('change',handleDelegatedChange);document.addEventListener('click',handleDelegatedClick);
  $('#onboardingNext').addEventListener('click',advanceOnboarding);$('#onboardingBack').addEventListener('click',()=>showOnboardingStep(onboardingStep-1));$('#onboardingSkip').addEventListener('click',dismissOnboarding);$('#onboardingModal').addEventListener('close',()=>{if(!settings.onboardingDismissed){settings.onboardingDismissed=true;persistSettings()}});$$('input[name="onboarding-income-type"]').forEach((input)=>input.addEventListener('change',updateOnboardingFields));['onboardingIncomeAmount','onboardingHours'].forEach((id)=>$(`#${id}`).addEventListener('input',updateOnboardingPreview));
}

function navRoot(view){return Object.entries(NAV_GROUPS).find(([,views])=>views.includes(view))?.[0]||'overview'}
function renderSectionNav(){const root=navRoot(activeView),views=NAV_GROUPS[root];$('#sectionNav').hidden=root==='overview';$('#sectionNav').innerHTML=root==='overview'?'':`<span>${root==='budget'?'Everyday money':root==='plan'?'Plan ahead':'More tools'}</span>${views.map((view)=>`<button class="${view===activeView?'active':''}" data-section-view="${view}">${NAV_LABELS[view]}</button>`).join('')}`;$$('[data-section-view]',$('#sectionNav')).forEach((button)=>button.addEventListener('click',()=>showView(button.dataset.sectionView)))}
function showView(view,updateHash=true){activeView=view;$$('.view').forEach((item)=>item.classList.toggle('active',item.dataset.view===view));const root=navRoot(view);$$('.nav-item').forEach((item)=>item.classList.toggle('active',item.dataset.navRoot===root));renderSectionNav();if(updateHash&&location.hash!==`#${view}`)history.replaceState(null,'',`#${view}`);renderAll();window.scrollTo({top:0,behavior:'smooth'})}
function applyRoute(){const view=location.hash.slice(1);showView(['overview','budget','transactions','bills','earnings','savings','retirement','assets','reports'].includes(view)?view:'overview',false)}
function renderAll(){populateControls();renderOverview();renderBudget();renderTransactions();renderBills();renderEarnings();renderSavings();renderRetirement();renderAssets();renderReports()}

function populateControls(){
  const parents=state.categories.filter((item)=>!item.parent_id).sort(sortOrder);$('#categoryParent').innerHTML='<option value="">Top-level category</option>'+parents.map((item)=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('');
  const categoryOptions=state.categories.filter((item)=>item.active).sort(sortOrder).map((item)=>`<option value="${item.id}">${item.parent_id?'— ':''}${escapeHtml(item.name)}</option>`).join('');['transactionCategory','billCategory'].forEach((id)=>{const value=$(`#${id}`).value;$(`#${id}`).innerHTML=`<option value="">Uncategorized</option>${categoryOptions}`;$(`#${id}`).value=value});
  const assetOptions=state.assets.filter((item)=>item.active).map((item)=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('');const assetValue=$('#transactionAsset').value;$('#transactionAsset').innerHTML=`<option value="">None</option>${assetOptions}`;$('#transactionAsset').value=assetValue;
  const sourceOptions=state.incomeSources.filter((item)=>item.active).map((item)=>`<option value="${item.id}">${escapeHtml(item.name)}</option>`).join('');['transactionIncomeSource','workSource','paycheckSource'].forEach((id)=>{const value=$(`#${id}`).value;$(`#${id}`).innerHTML=`<option value="">${id==='transactionIncomeSource'?'None':'Choose source'}</option>${sourceOptions}`;$(`#${id}`).value=value});
  const goalValue=$('#contributionGoal').value;$('#contributionGoal').innerHTML='<option value="">Choose goal</option>'+state.savingsGoals.filter(x=>x.active).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');$('#contributionGoal').value=goalValue;
  const accountValue=$('#allocationAccount').value;$('#allocationAccount').innerHTML='<option value="">Choose account</option>'+state.retirementAccounts.filter(x=>x.active).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');$('#allocationAccount').value=accountValue;
}

function monthKey(date=new Date()){return date.toISOString().slice(0,7)}
function monthBounds(month){const start=`${month}-01`;const date=new Date(`${start}T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()+1);return{start,end:date.toISOString().slice(0,10)}}
function isExpectedOnlyTransaction(item){return item.paycheck_id&&state.paychecks.some(paycheck=>paycheck.id===item.paycheck_id&&paycheck.status!=='reconciled')}
function monthlyTransactions(month){const{start,end}=monthBounds(month);return state.transactions.filter((item)=>item.transaction_date>=start&&item.transaction_date<end&&!isExpectedOnlyTransaction(item))}
function renderOverview(){
  const month=$('#overviewMonth').value||monthKey(),transactions=monthlyTransactions(month),income=sum(transactions.filter((x)=>x.transaction_type==='income'),'amount_minor'),spending=sum(transactions.filter((x)=>x.transaction_type==='expense'),'amount_minor'),left=income-spending;
  const paychecks=state.paychecks.filter((item)=>item.pay_date.startsWith(month)),takeHome=paychecks.filter(x=>x.status==='reconciled').reduce((total,item)=>total+reconciledPay(item).netMinor,0),expected=expectedMonthlyIncome(),savedThisMonth=sum(state.contributions.filter(x=>x.contribution_date.startsWith(month)),'amount_minor'),savings=state.savingsGoals.reduce((total,item)=>total+Number(item.current_minor),0),worth=netWorth(state.assets),budgets=state.budgets.filter((item)=>String(item.budget_month).startsWith(month)),budgeted=sum(budgets,'amount_minor');
  const monthName=new Date(`${month}-01T00:00:00Z`).toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'});
  $('#overviewHero').innerHTML=`<div class="month-story-heading"><span>${escapeHtml(monthName)}</span><small>${expected?`${formatMoney(expected)} expected before deductions`:'Add a job to see expected income'}</small></div><div class="story-grid">${storyMetric('Received',income,'Money recorded as income','income')}${storyMetric('Spent',spending,'Expenses recorded this month','expense')}${storyMetric('Left',left,'Received minus spending','left')}${storyMetric('Saved',savedThisMonth,savedThisMonth?'Contributions this month':'Record a contribution','saved')}</div>`;
  $('#overviewSecondaryStats').innerHTML=[['Take-home received',takeHome,takeHome?'From reconciled paychecks':'No actual paycheck yet'],['Budget used',spending,budgeted?`${Math.round(spending/budgeted*100)}% of ${formatMoney(budgeted)}`:'Set a monthly budget'],['Total savings',savings,`${savingsRate(income,spending)}% monthly savings rate`],['Net worth',worth.netWorthMinor,`${formatMoney(worth.assetsMinor)} in assets`]].map(([label,value,detail])=>`<article><span>${label}</span><strong>${formatMoney(value)}</strong><small>${detail}</small></article>`).join('');renderCashflowChart(month);
  const upcoming=[...state.bills].filter((item)=>item.active).sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date)).slice(0,5);$('#upcomingBills').innerHTML=upcoming.length?upcoming.map(billPreviewRow).join(''):friendlyEmpty('No bills on the horizon.','Add a recurring bill so upcoming payments appear here.','Add bill','bills');
  const rollups=categoryRollups(state.categories,state.transactions,month),budgetMap=new Map(budgets.map(x=>[x.category_id,x]));const top=state.categories.filter((item)=>!item.parent_id&&item.category_type==='expense').sort((a,b)=>(rollups.get(b.id)||0)-(rollups.get(a.id)||0)).slice(0,5);$('#overviewBudget').innerHTML=top.length?top.map((item)=>overviewBudgetRow(item,rollups.get(item.id)||0,Number(budgetMap.get(item.id)?.amount_minor||0))).join(''):friendlyEmpty('Your budget is ready when you are.','Add a category and monthly amount to start tracking progress.','Build a budget','budget');
  const recent=[...transactions].sort((a,b)=>b.transaction_date.localeCompare(a.transaction_date)).slice(0,5);$('#recentTransactions').innerHTML=recent.length?recent.map(transactionRow).join(''):friendlyEmpty('No activity this month.','Add income or an expense to start your monthly picture.','Add an expense','transactions');
}
function storyMetric(label,value,detail,tone){return`<article class="story-metric ${tone}"><span>${label}</span><strong>${formatMoney(value)}</strong><small>${detail}</small></article>`}
function billPreviewRow(item){const date=new Date(`${item.next_due_date}T00:00:00Z`);return`<article class="bill-preview"><time datetime="${item.next_due_date}"><b>${date.toLocaleDateString('en-US',{month:'short',timeZone:'UTC'})}</b><strong>${date.getUTCDate()}</strong></time><div><h3>${escapeHtml(item.name)}</h3><p>${humanFrequency(item.frequency)}</p></div><strong>${formatMoney(item.amount_minor)}</strong></article>`}
function overviewBudgetRow(item,spent,budget){const progress=budget?Math.min(100,Math.round(spent/budget*100)):0;return`<button class="overview-budget-row" data-go-to="budget"><span class="category-icon">${categoryIcon(item.name)}</span><span><b>${escapeHtml(item.name)}</b><small>${budget?`${formatMoney(spent)} of ${formatMoney(budget)}`:`${formatMoney(spent)} spent · add a budget`}</small><i><em style="width:${progress}%"></em></i></span><strong>${budget?`${progress}%`:'—'}</strong></button>`}
function renderCashflowChart(month){const months=[];const date=new Date(`${month}-01T00:00:00Z`);for(let i=5;i>=0;i--){const d=new Date(date);d.setUTCMonth(d.getUTCMonth()-i);const key=d.toISOString().slice(0,7),items=monthlyTransactions(key);months.push({label:d.toLocaleDateString('en-US',{month:'short',timeZone:'UTC'}),income:sum(items.filter(x=>x.transaction_type==='income'),'amount_minor'),expense:sum(items.filter(x=>x.transaction_type==='expense'),'amount_minor')})}const max=Math.max(1,...months.flatMap(x=>[x.income,x.expense]));$('#cashflowChart').innerHTML=months.flatMap(item=>[{label:`${item.label} in`,value:item.income},{label:`${item.label} out`,value:item.expense}]).map(item=>bar(item.label,item.value,max)).join('')}

async function ensureBudgetMonth(month){if(state.budgets.some((item)=>String(item.budget_month).startsWith(month)))return;const prior=state.budgets.filter((item)=>String(item.budget_month).slice(0,7)<month).sort((a,b)=>String(b.budget_month).localeCompare(String(a.budget_month)));if(!prior.length)return;const latest=String(prior[0].budget_month).slice(0,7),copies=prior.filter((item)=>String(item.budget_month).startsWith(latest)).map((item)=>({id:crypto.randomUUID(),user_id:currentUser.id,category_id:item.category_id,budget_month:`${month}-01`,amount_minor:item.amount_minor}));if(!copies.length)return;const{data,error}=await client.from(TABLES.budgets).insert(copies).select();if(error)throw error;state.budgets.push(...data)}
function renderBudget(){
  const month=$('#budgetMonth').value||monthKey(),rollups=categoryRollups(state.categories,state.transactions,month),budgetMap=new Map(state.budgets.filter((item)=>String(item.budget_month).startsWith(month)).map((item)=>[item.category_id,item]));
  const parents=state.categories.filter((item)=>!item.parent_id&&item.category_type==='expense').sort(sortOrder);$('#budgetList').innerHTML=parents.length?parents.map((parent)=>{const children=state.categories.filter((item)=>item.parent_id===parent.id).sort(sortOrder);return`<section class="budget-group">${budgetRow(parent,budgetMap.get(parent.id),rollups.get(parent.id)||0,true)}${children.map((child)=>budgetRow(child,budgetMap.get(child.id),rollups.get(child.id)||0,false)).join('')}</section>`}).join(''):empty('Create an expense category to begin.');
}
function budgetRow(category,budget,spent,isParent){const amount=Number(budget?.amount_minor||0),remaining=budgetRemaining(amount,spent),progress=amount?Math.min(100,Math.round(spent/amount*100)):0;return`<div class="${isParent?'budget-parent':'budget-child'}"><div class="budget-identity">${isParent?`<span class="category-icon">${categoryIcon(category.name)}</span>`:''}<span><strong>${escapeHtml(category.name)}</strong>${isParent?`<small>${formatMoney(spent)} of ${formatMoney(amount)} · ${formatMoney(remaining)} left</small><div class="progress" aria-label="${progress}% of budget used"><i style="width:${progress}%"></i></div>`:''}</span></div><label class="budget-cell">Monthly budget<input class="budget-input" data-budget-category="${category.id}" value="${(amount/100).toFixed(2)}" inputmode="decimal"></label><span class="budget-cell spent">Spent<b>${formatMoney(spent)}</b></span><span class="budget-cell remaining">Left<b>${formatMoney(remaining)}</b></span><span class="row-actions"><button class="small-action" data-action="move-category-up" data-id="${category.id}" aria-label="Move ${escapeHtml(category.name)} up">↑</button><button class="small-action" data-action="edit-category" data-id="${category.id}">Edit</button><button class="small-action danger" data-action="delete-category" data-id="${category.id}">Delete</button></span></div>`}

function renderTransactions(){const search=$('#transactionSearch').value.trim().toLowerCase(),filter=$('#transactionFilter').value,sort=$('#transactionSort').value;let items=state.transactions.filter((item)=>!isExpectedOnlyTransaction(item)&&(filter==='all'||item.transaction_type===filter)&&(!search||`${item.description} ${item.notes}`.toLowerCase().includes(search)));items.sort(sort==='oldest'?(a,b)=>a.transaction_date.localeCompare(b.transaction_date):sort==='largest'?(a,b)=>b.amount_minor-a.amount_minor:sort==='smallest'?(a,b)=>a.amount_minor-b.amount_minor:(a,b)=>b.transaction_date.localeCompare(a.transaction_date));$('#transactionList').innerHTML=items.length?items.map(transactionRow).join(''):friendlyEmpty('No transactions match.','Record income or an expense, or adjust your filters.','Add an expense','transactions')}
function transactionRow(item){const category=state.categories.find((x)=>x.id===item.category_id),asset=state.assets.find((x)=>x.id===item.asset_id);return`<article class="list-row"><div><h3>${escapeHtml(item.description)}</h3><p>${item.transaction_date}${category?` · ${escapeHtml(category.name)}`:''}${asset?` · ${escapeHtml(asset.name)}`:''}</p></div><strong class="money-value ${item.transaction_type}">${item.transaction_type==='expense'?'−':'+'}${formatMoney(item.amount_minor)}</strong><span class="row-actions"><button class="small-action" data-action="edit-transaction" data-id="${item.id}">Edit</button><button class="small-action danger" data-action="delete-transaction" data-id="${item.id}">Delete</button></span></article>`}

function renderBills(){const active=state.bills.filter((item)=>item.active).sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date));$('#billCommitment').textContent=`${formatMoney(active.reduce((sum,item)=>sum+monthlyBillAmount(item),0))} / month`;$('#billList').innerHTML=state.bills.length?[...state.bills].sort((a,b)=>a.next_due_date.localeCompare(b.next_due_date)).map((item)=>{const date=new Date(`${item.next_due_date}T00:00:00Z`);return`<article class="bill-card${item.active?'':' inactive'}"><time datetime="${item.next_due_date}"><b>${date.toLocaleDateString('en-US',{month:'short',timeZone:'UTC'})}</b><strong>${date.getUTCDate()}</strong></time><div><h3>${escapeHtml(item.name)}</h3><p>${humanFrequency(item.frequency)} · ${item.classification}${item.active?'':' · inactive'}</p></div><strong>${formatMoney(item.amount_minor)}</strong><span class="row-actions"><button class="small-action" data-action="record-bill" data-id="${item.id}">Record paid</button><button class="small-action" data-action="edit-bill" data-id="${item.id}">Edit</button><button class="small-action danger" data-action="delete-bill" data-id="${item.id}">Delete</button></span></article>`}).join(''):friendlyEmpty('No recurring bills yet.','Add rent, utilities, subscriptions, or anything else you want to see coming.','Add your first bill','bills')}

function renderEarnings(){
  const expected=expectedMonthlyIncome(),month=monthKey(),received=sum(monthlyTransactions(month).filter(x=>x.transaction_type==='income'),'amount_minor');$('#earningsSummary').innerHTML=`<article><span>Expected</span><strong>${formatMoney(expected)}</strong><small>Monthly gross from active sources</small></article><article><span>Received</span><strong>${formatMoney(received)}</strong><small>Income actually recorded this month</small></article><article><span>Difference</span><strong>${formatMoney(received-expected)}</strong><small>Received minus expected</small></article>`;
  $('#incomeSourceList').innerHTML=state.incomeSources.length?state.incomeSources.map(incomeSourceCard).join(''):friendlyEmpty('Add your job or another source of income.','You’ll immediately see an understandable monthly and paycheck estimate.','Add income','earnings');
  const work=state.workEntries.map((item)=>({date:item.work_date,markup:`<article class="list-row"><div><h3>${escapeHtml(sourceName(item.income_source_id))} work</h3><p>${item.work_date} · ${formatHours(item.regular_minutes+item.overtime_minutes)}${item.overtime_minutes?` (${formatHours(item.overtime_minutes)} OT)`:''}</p></div><strong>${formatMoney(item.estimated_gross_minor)} est.</strong><span class="row-actions"><button class="small-action danger" data-action="delete-work" data-id="${item.id}">Delete</button></span></article>`}));
  const pay=state.paychecks.map((item)=>{const reconciled=reconciledPay(item);return{date:item.pay_date,markup:`<article class="list-row"><div><h3>${escapeHtml(sourceName(item.income_source_id))} paycheck</h3><p>${item.period_start} – ${item.period_end} · ${item.status==='reconciled'?'Received':'Expected'}</p></div><strong>${formatMoney(reconciled.netMinor)} ${item.status==='reconciled'?'received':'expected'}</strong><span class="row-actions"><button class="small-action" data-action="edit-paycheck" data-id="${item.id}">View details</button><button class="small-action danger" data-action="delete-paycheck" data-id="${item.id}">Delete</button></span></article>`}});$('#earningsList').innerHTML=[...work,...pay].sort((a,b)=>b.date.localeCompare(a.date)).map((x)=>x.markup).join('')||friendlyEmpty('No hours or paychecks yet.','Hourly work and actual pay will appear here when you choose to track them.','Track earnings','earnings');updateIncomeSourceExperience();updateWorkEstimate();updatePayEstimate();
}
function incomeSourceCard(item){const monthly=sourceExpectedMonthly(item),paycheck=sourceExpectedPaycheck(item),type=item.income_type.replace('_',' ');let primary='',detail='';if(item.hourly_rate_minor!=null){primary=`${formatMoney(item.hourly_rate_minor)} / hour`;detail=item.standard_weekly_minutes?`${formatHours(item.standard_weekly_minutes)} expected weekly · ≈ ${formatMoney(monthly)} / month gross`:'Add expected hours or track worked hours to estimate income.'}else if(item.annual_salary_minor!=null){primary=`${formatMoney(item.annual_salary_minor)} / year`;detail=`≈ ${formatMoney(monthly)} / month gross${paycheck?` · ≈ ${formatMoney(paycheck)} per paycheck`:''}`}else{primary='Amount not set';detail='Add an expected amount when you are ready.'}return`<article class="income-card"><div class="income-card-top"><span class="category-icon">${item.hourly_rate_minor!=null?'⏱':'◎'}</span><span><small>${escapeHtml(type)} · ${humanFrequency(item.pay_frequency)}</small><h3>${escapeHtml(item.name)}</h3></span><i>${item.active?'Active':'Inactive'}</i></div><strong>${primary}</strong><p>${detail}</p><div class="row-actions"><button class="small-action" data-action="edit-income-source" data-id="${item.id}">View details</button><button class="small-action danger" data-action="delete-income-source" data-id="${item.id}">Delete</button></div></article>`}

function renderSavings(){const goal=state.savingsGoals[0];if(goal){const points=savingsProjection(goal.current_minor,goal.monthly_contribution_minor,24);$('#savingsChart').innerHTML=lineChart(points.map((p)=>p.valueMinor))}else $('#savingsChart').innerHTML=friendlyEmpty('No projection yet.','Add a goal and optional monthly contribution to explore a scenario.','Add a goal','savings');$('#savingsList').innerHTML=state.savingsGoals.length?state.savingsGoals.map((item)=>{const progress=Math.min(100,Math.round(item.current_minor/item.target_minor*100)),remaining=Math.max(0,item.target_minor-item.current_minor),months=item.monthly_contribution_minor?Math.ceil(remaining/item.monthly_contribution_minor):null;return`<article class="savings-card"><div class="savings-ring" style="--progress:${progress}%"><strong>${progress}%</strong></div><div><p class="eyebrow">Savings goal</p><h3>${escapeHtml(item.name)}</h3><strong>${formatMoney(item.current_minor)} <small>of ${formatMoney(item.target_minor)}</small></strong><div class="progress"><i style="width:${progress}%"></i></div><p>${formatMoney(remaining)} to go${months==null?'':` · about ${months} months`}</p><span class="row-actions"><button class="small-action" data-action="edit-savings" data-id="${item.id}">Edit goal</button><button class="small-action danger" data-action="delete-savings" data-id="${item.id}">Delete</button></span></div></article>`}).join(''):friendlyEmpty('What are you saving for?','Create a goal and watch each contribution move you closer.','Add your first goal','savings');$('#contributionList').innerHTML=state.contributions.length?[...state.contributions].sort((a,b)=>b.contribution_date.localeCompare(a.contribution_date)).slice(0,10).map(item=>simpleRow(state.savingsGoals.find(x=>x.id===item.savings_goal_id)?.name||'Savings goal',`${item.contribution_date}${item.notes?` · ${item.notes}`:''}`,formatMoney(item.amount_minor))).join(''):empty('Contributions will appear here.')}

function renderRetirement(){const profile=state.retirementProfiles[0];if(profile)fillRetirementForm(profile,false);const input=retirementInput();const result=retirementProjection(input);$('#retirementStats').innerHTML=[['Projected',result.balanceMinor],['Your contributions',result.userContributionsMinor],['Employer contributions',result.employerContributionsMinor],['Estimated growth',result.growthMinor]].map(([label,value])=>`<div class="mini-stat"><span>${label}</span><strong>${formatMoney(value)}</strong></div>`).join('');$('#retirementChart').innerHTML=lineChart(result.points.map((p)=>p.balanceMinor));$('#retirementAccounts').innerHTML=state.retirementAccounts.length?state.retirementAccounts.map((item)=>`<article class="list-row"><div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.account_type)}</p></div><strong>${formatMoney(item.current_balance_minor)}</strong><span class="row-actions"><button class="small-action danger" data-action="delete-retirement-account" data-id="${item.id}">Delete</button></span></article>`).join(''):empty('No retirement accounts yet.');$('#allocationList').innerHTML=state.allocations.length?state.allocations.map(item=>`<article class="list-row"><div><h3>${escapeHtml(item.asset_class)}</h3><p>${escapeHtml(state.retirementAccounts.find(x=>x.id===item.retirement_account_id)?.name||'Account')} · current ${item.current_basis_points/100}% · target ${item.target_basis_points/100}%</p></div><span class="row-actions"><button class="small-action danger" data-action="delete-allocation" data-id="${item.id}">Delete</button></span></article>`).join(''):empty('No allocation targets yet.')}

function renderAssets(){const worth=netWorth(state.assets);$('#netWorthStats').innerHTML=[['Assets',worth.assetsMinor,'What you own'],['Liabilities',worth.liabilitiesMinor,'What you owe'],['Net worth',worth.netWorthMinor,'Assets minus liabilities'],['Ownership costs',sum(state.transactions.filter((item)=>item.asset_id&&item.transaction_type==='expense'),'amount_minor'),'Asset-linked expenses']].map(([a,b,c],i)=>statCard(a,b,c,i===2)).join('');$('#assetList').innerHTML=state.assets.length?state.assets.map((item)=>`<article class="list-row"><div><h3>${escapeHtml(item.name)}</h3><p>${item.asset_group.replaceAll('_',' ')} · ${escapeHtml(item.asset_type)}</p></div><strong>${formatMoney(item.current_value_minor)}</strong><span class="row-actions"><button class="small-action" data-action="edit-asset" data-id="${item.id}">Edit</button><button class="small-action danger" data-action="delete-asset" data-id="${item.id}">Delete</button></span></article>`).join(''):friendlyEmpty('Net worth is optional.','Add an account, property, or liability whenever this view becomes useful to you.','Add an asset','assets');const snapshots=[...state.snapshots].sort((a,b)=>a.snapshot_date.localeCompare(b.snapshot_date));$('#netWorthChart').innerHTML=snapshots.length>1?lineChart(snapshots.map((item)=>item.net_worth_minor)):empty('Save snapshots over time to build net-worth history.')}

function renderReports(){const range=$('#reportRange').value;$('#customReportDates').hidden=range!=='custom';const{start,end}=reportBounds(range),transactions=state.transactions.filter((item)=>item.transaction_date>=start&&item.transaction_date<=end&&!isExpectedOnlyTransaction(item)),income=sum(transactions.filter(x=>x.transaction_type==='income'),'amount_minor'),expense=sum(transactions.filter(x=>x.transaction_type==='expense'),'amount_minor'),fixed=fixedVariableTotals(transactions,state.categories),paychecks=state.paychecks.filter((item)=>item.pay_date>=start&&item.pay_date<=end),work=state.workEntries.filter((item)=>item.work_date>=start&&item.work_date<=end);const gross=paychecks.reduce((s,p)=>s+reconciledPay(p).grossMinor,0),net=paychecks.reduce((s,p)=>s+reconciledPay(p).netMinor,0),withholding=paychecks.reduce((s,p)=>s+Number(p.actual_federal_minor||p.estimated_federal_minor||0)+Number(p.actual_state_minor||p.estimated_state_minor||0)+Number(p.actual_social_security_minor||p.estimated_social_security_minor||0)+Number(p.actual_medicare_minor||p.estimated_medicare_minor||0),0),retirement=paychecks.reduce((s,p)=>s+Number(p.actual_retirement_minor||p.estimated_retirement_minor||0)+Number(p.employer_retirement_minor||0),0);$('#reportStats').innerHTML=[['Income',income,'Transactions'],['Expenses',expense,`${savingsRate(income,expense)}% savings rate`],['Gross pay',gross,`${formatHours(work.reduce((s,w)=>s+w.regular_minutes+w.overtime_minutes,0))} worked`],['Net pay',net,`${formatMoney(withholding)} withheld`],['Fixed',fixed.fixedMinor,'Fixed spending'],['Variable',fixed.variableMinor,'Variable spending'],['Retirement',retirement,'Employee + employer'],['Recurring',state.bills.filter(b=>b.active).reduce((s,b)=>s+monthlyBillAmount(b),0),'Monthly equivalent']].map(([a,b,c])=>statCard(a,b,c)).join('');const categoryTotals=new Map();transactions.filter(x=>x.transaction_type==='expense').forEach(x=>categoryTotals.set(x.category_id,(categoryTotals.get(x.category_id)||0)+Number(x.amount_minor)));const categories=[...categoryTotals].map(([id,value])=>({label:state.categories.find(x=>x.id===id)?.name||'Uncategorized',value})).sort((a,b)=>b.value-a.value);const max=Math.max(1,...categories.map(x=>x.value));$('#reportCategoryChart').innerHTML=categories.length?categories.slice(0,8).map(x=>bar(x.label,x.value,max)).join(''):empty('No spending in this range.');const assetCosts=new Map();transactions.filter(x=>x.asset_id&&x.transaction_type==='expense').forEach(x=>assetCosts.set(x.asset_id,(assetCosts.get(x.asset_id)||0)+Number(x.amount_minor)));$('#reportDetails').innerHTML=[...assetCosts].map(([id,value])=>simpleRow(state.assets.find(x=>x.id===id)?.name||'Asset','Ownership cost',formatMoney(value))).join('')||empty('Asset-linked costs will appear here.')}

async function saveCategory(event){event.preventDefault();try{const id=$('#categoryId').value||crypto.randomUUID();await saveRow('categories',{id,name:$('#categoryName').value.trim(),parent_id:$('#categoryParent').value||null,category_type:$('#categoryType').value,classification:$('#categoryClassification').value||null,sort_order:state.categories.find(x=>x.id===id)?.sort_order??state.categories.length*10,active:true});event.target.reset();$('#categoryId').value='';populateControls();renderAll()}catch{alert('Category could not be saved. Names and relationships must be valid.')}}
async function saveTransaction(event){event.preventDefault();try{const id=$('#transactionId').value||crypto.randomUUID();await saveRow('transactions',{id,transaction_type:$('#transactionType').value,amount_minor:parsePositive($('#transactionAmount').value),description:$('#transactionDescription').value.trim(),transaction_date:$('#transactionDate').value,category_id:$('#transactionCategory').value||null,asset_id:$('#transactionAsset').value||null,income_source_id:$('#transactionIncomeSource').value||null,paycheck_id:null,bill_id:null,bill_due_date:null,notes:$('#transactionNotes').value.trim()});event.target.reset();$('#transactionId').value='';setDefaultDates();renderAll()}catch{alert('Transaction could not be saved. Check the amount and required fields.')}}
async function saveBill(event){event.preventDefault();try{const id=$('#billId').value||crypto.randomUUID();await saveRow('bills',{id,name:$('#billName').value.trim(),amount_minor:parsePositive($('#billAmount').value),category_id:$('#billCategory').value||null,next_due_date:$('#billDate').value,frequency:$('#billFrequency').value,custom_interval_days:$('#billFrequency').value==='custom'?Number($('#billCustomDays').value):null,classification:$('#billClassification').value,notes:$('#billNotes').value.trim(),active:$('#billActive').checked,last_materialized_due_date:state.bills.find(x=>x.id===id)?.last_materialized_due_date||null});event.target.reset();$('#billId').value='';$('#billActive').checked=true;renderAll()}catch{alert('Bill could not be saved. Custom recurrence requires an interval.')}}
async function saveIncomeSource(event){event.preventDefault();try{const id=$('#incomeSourceId').value||crypto.randomUUID(),type=$('#incomeSourceType').value,hours=Number($('#incomeExpectedHours').value||0);await saveRow('incomeSources',{id,name:$('#incomeSourceName').value.trim(),income_type:type,hourly_rate_minor:type==='hourly'?parsePositive($('#incomeHourlyRate').value):null,annual_salary_minor:type==='hourly'?null:(type==='salary'?parsePositive($('#incomeSalary').value):optionalMoney($('#incomeSalary').value)),pay_frequency:$('#incomeFrequency').value,standard_weekly_minutes:type==='hourly'&&hours?Math.round(hours*60):null,overtime_multiplier_basis_points:Math.round(Number($('#incomeOvertime').value||1.5)*10000),notes:'',active:true});event.target.reset();$('#incomeSourceId').value='';$('#incomeSourceType').value='salary';populateControls();renderAll()}catch{alert('Income source could not be saved. Hourly work needs a rate; salary work needs an annual amount.')}}
async function saveWork(event){event.preventDefault();try{const source=state.incomeSources.find(x=>x.id===$('#workSource').value);if(!source||source.hourly_rate_minor==null)throw Error();const regular=Math.round(Number($('#workRegular').value)*60),overtime=Math.round(Number($('#workOvertime').value||0)*60);await saveRow('workEntries',{id:crypto.randomUUID(),income_source_id:source.id,work_date:$('#workDate').value,starts_at:null,ends_at:null,regular_minutes:regular,overtime_minutes:overtime,estimated_gross_minor:hourlyGross(source.hourly_rate_minor,regular,overtime,source.overtime_multiplier_basis_points),notes:$('#workNotes').value.trim(),source_app:null,source_type:null,source_id:null});event.target.reset();setDefaultDates();renderAll()}catch{alert('Work entry needs an hourly source and valid hours.')}}
async function savePaycheck(event){event.preventDefault();try{const id=$('#paycheckId').value||crypto.randomUUID(),estimate=currentPayEstimate(),actualNet=optionalMoney($('#actualNet').value),status=actualNet==null?'estimated':'reconciled';const paycheck=await saveRow('paychecks',{id,income_source_id:$('#paycheckSource').value,period_start:$('#payPeriodStart').value,period_end:$('#payPeriodEnd').value,pay_date:$('#payDate').value,status,estimated_gross_minor:estimate.grossMinor,estimated_pre_tax_minor:parseZero($('#payPreTax').value),estimated_federal_minor:estimate.federalMinor,estimated_state_minor:estimate.stateMinor,estimated_social_security_minor:estimate.socialSecurityMinor,estimated_medicare_minor:estimate.medicareMinor,estimated_post_tax_minor:parseZero($('#payPostTax').value),estimated_retirement_minor:parseZero($('#payRetirement').value),estimated_benefits_minor:parseZero($('#payBenefits').value),estimated_net_minor:estimate.netMinor,actual_gross_minor:optionalMoney($('#actualGross').value),actual_federal_minor:optionalMoney($('#actualFederal').value),actual_state_minor:optionalMoney($('#actualState').value),actual_social_security_minor:optionalMoney($('#actualSocialSecurity').value),actual_medicare_minor:optionalMoney($('#actualMedicare').value),actual_retirement_minor:optionalMoney($('#actualRetirement').value),employer_retirement_minor:optionalMoney($('#actualEmployerRetirement').value),actual_benefits_minor:optionalMoney($('#actualBenefits').value),actual_other_deductions_minor:optionalMoney($('#actualOther').value),actual_net_minor:actualNet,notes:''});if(status==='reconciled'){const amount=reconciledPay(paycheck).netMinor,existing=state.transactions.find(x=>x.paycheck_id===id);await saveRow('transactions',{id:existing?.id||crypto.randomUUID(),transaction_type:'income',amount_minor:amount,description:`${sourceName(paycheck.income_source_id)} paycheck`,transaction_date:paycheck.pay_date,category_id:state.categories.find(x=>x.category_type==='income'&&!x.parent_id)?.id||null,asset_id:null,income_source_id:paycheck.income_source_id,paycheck_id:id,bill_id:null,bill_due_date:null,notes:'Actual reconciled net pay'})}event.target.reset();$('#paycheckId').value='';setDefaultDates();renderAll()}catch{alert('Paycheck could not be saved. Check the period, source, amounts, and actual net value.')}}
async function saveSavingsGoal(event){event.preventDefault();try{const id=$('#savingsId').value||crypto.randomUUID();await saveRow('savingsGoals',{id,name:$('#savingsName').value.trim(),current_minor:parseZero($('#savingsCurrent').value),target_minor:parsePositive($('#savingsTarget').value),monthly_contribution_minor:parseZero($('#savingsMonthly').value),target_date:$('#savingsDate').value||null,notes:$('#savingsNotes').value.trim(),active:true});event.target.reset();$('#savingsId').value='';renderAll()}catch{alert('Savings goal could not be saved.')}}
async function saveContribution(event){event.preventDefault();try{const goal=state.savingsGoals.find(x=>x.id===$('#contributionGoal').value),amount=parsePositive($('#contributionAmount').value);if(!goal)throw Error();await saveRow('contributions',{id:crypto.randomUUID(),savings_goal_id:goal.id,transaction_id:null,contribution_date:$('#contributionDate').value,amount_minor:amount,notes:$('#contributionNotes').value.trim()});await saveRow('savingsGoals',{...goal,current_minor:Number(goal.current_minor)+amount});event.target.reset();setDefaultDates();renderAll()}catch{alert('Contribution could not be saved. Choose a goal and valid amount.')}}
async function saveRetirementProfile(event){event.preventDefault();try{const existing=state.retirementProfiles[0];await saveRow('retirementProfiles',{id:existing?.id||crypto.randomUUID(),current_age:Number($('#retCurrentAge').value),retirement_age:Number($('#retirementAge').value),annual_income_minor:parseZero($('#retIncome').value),employee_contribution_basis_points:Math.round(Number($('#retContribution').value)*100),employer_match_basis_points:Math.round(Number($('#retMatch').value)*100),employer_match_limit_basis_points:Math.round(Number($('#retMatchLimit').value)*100),additional_annual_minor:parseZero($('#retAdditional').value),expected_return_basis_points:Math.round(Number($('#retReturn').value)*100),inflation_basis_points:Math.round(Number($('#retInflation').value||0)*100)});renderAll()}catch{alert('Retirement assumptions could not be saved. Retirement age must be greater than current age.')}}
async function saveRetirementAccount(event){event.preventDefault();try{await saveRow('retirementAccounts',{id:crypto.randomUUID(),name:$('#retAccountName').value.trim(),account_type:$('#retAccountType').value.trim(),current_balance_minor:parseZero($('#retAccountBalance').value),notes:'',active:true});event.target.reset();renderAll()}catch{alert('Retirement account could not be saved.')}}
async function saveAllocation(event){event.preventDefault();try{await saveRow('allocations',{id:crypto.randomUUID(),retirement_account_id:$('#allocationAccount').value,asset_class:$('#allocationClass').value.trim(),current_basis_points:Math.round(Number($('#allocationCurrent').value)*100),target_basis_points:Math.round(Number($('#allocationTarget').value)*100)});event.target.reset();renderAll()}catch{alert('Allocation could not be saved. Percentages must be between 0 and 100.')}}
async function saveAsset(event){event.preventDefault();try{const id=$('#assetId').value||crypto.randomUUID();await saveRow('assets',{id,name:$('#assetName').value.trim(),asset_group:$('#assetGroup').value,asset_type:$('#assetType').value.trim(),current_value_minor:parseZero($('#assetValue').value),purchase_date:$('#assetPurchaseDate').value||null,purchase_price_minor:optionalMoney($('#assetPurchasePrice').value),notes:$('#assetNotes').value.trim(),metadata:{},active:true});event.target.reset();$('#assetId').value='';populateControls();renderAll()}catch{alert('Asset could not be saved.')}}
async function saveNetWorthSnapshot(){const worth=netWorth(state.assets);try{await saveRow('snapshots',{id:state.snapshots.find(x=>x.snapshot_date===today())?.id||crypto.randomUUID(),snapshot_date:today(),assets_minor:worth.assetsMinor,liabilities_minor:worth.liabilitiesMinor});renderAssets()}catch{alert('Today’s net-worth snapshot could not be saved.')}}

async function handleDelegatedChange(event){if(event.target.matches('[data-budget-category]')){try{const categoryId=event.target.dataset.budgetCategory,month=$('#budgetMonth').value,existing=state.budgets.find(x=>x.category_id===categoryId&&String(x.budget_month).startsWith(month));await saveRow('budgets',{id:existing?.id||crypto.randomUUID(),category_id:categoryId,budget_month:`${month}-01`,amount_minor:parseZero(event.target.value)});renderAll()}catch{alert('Budget amount could not be saved.')}}}
async function handleDelegatedClick(event){const goTo=event.target.closest('[data-go-to]');if(goTo){settingsModalClose();showView(goTo.dataset.goTo);return}const button=event.target.closest('[data-action]');if(!button)return;const{id,action}=button.dataset;try{
  if(action==='edit-category')fillCategory(state.categories.find(x=>x.id===id));
  if(action==='delete-category'&&confirm('Delete this category? Categories in use must be reassigned first.')){await removeRow('categories',id);renderAll()}
  if(action==='move-category-up'){const item=state.categories.find(x=>x.id===id);await saveRow('categories',{...item,sort_order:Math.max(0,item.sort_order-11)});renderAll()}
  if(action==='edit-transaction')fillTransaction(state.transactions.find(x=>x.id===id));
  if(action==='delete-transaction'&&confirm('Delete this transaction permanently?')){await removeRow('transactions',id);renderAll()}
  if(action==='edit-bill')fillBill(state.bills.find(x=>x.id===id));
  if(action==='delete-bill'&&confirm('Delete this bill? Recorded transactions remain.')){await removeRow('bills',id);renderAll()}
  if(action==='record-bill')await recordBill(state.bills.find(x=>x.id===id));
  if(action==='edit-income-source')fillIncomeSource(state.incomeSources.find(x=>x.id===id));
  if(action==='delete-income-source'&&confirm('Delete this income source? Sources with work or paychecks must remain.')){await removeRow('incomeSources',id);renderAll()}
  if(action==='delete-work'&&confirm('Delete this work entry?')){await removeRow('workEntries',id);renderAll()}
  if(action==='edit-paycheck')fillPaycheck(state.paychecks.find(x=>x.id===id));
  if(action==='delete-paycheck'&&confirm('Delete this paycheck? Delete its linked income transaction first if present.')){await removeRow('paychecks',id);renderAll()}
  if(action==='edit-savings')fillSavings(state.savingsGoals.find(x=>x.id===id));
  if(action==='delete-savings'&&confirm('Delete this savings goal?')){await removeRow('savingsGoals',id);renderAll()}
  if(action==='delete-retirement-account'&&confirm('Delete this retirement account?')){await removeRow('retirementAccounts',id);renderAll()}
  if(action==='delete-allocation'&&confirm('Delete this allocation target?')){await removeRow('allocations',id);renderAll()}
  if(action==='edit-asset')fillAsset(state.assets.find(x=>x.id===id));
  if(action==='delete-asset'&&confirm('Delete this asset? Assets referenced by transactions must remain.')){await removeRow('assets',id);renderAll()}
}catch{alert('That change could not be completed. Related records may need to be removed or reassigned first.')}}

async function recordBill(bill){if(!bill)return;const existing=state.transactions.find(x=>x.bill_id===bill.id&&x.bill_due_date===bill.next_due_date);if(existing)return alert('This bill occurrence is already recorded.');const due=bill.next_due_date;await saveRow('transactions',{id:crypto.randomUUID(),transaction_type:'expense',amount_minor:Number(bill.amount_minor),description:bill.name,transaction_date:due,category_id:bill.category_id,asset_id:null,income_source_id:null,paycheck_id:null,bill_id:bill.id,bill_due_date:due,notes:`Recorded from ${bill.frequency} bill`});await saveRow('bills',{...bill,last_materialized_due_date:due,next_due_date:nextBillDate(bill,due)});renderAll()}
function nextBillDate(bill,value){const date=new Date(`${value}T00:00:00Z`),days={weekly:7,biweekly:14,custom:Number(bill.custom_interval_days||1)};if(days[bill.frequency])date.setUTCDate(date.getUTCDate()+days[bill.frequency]);else date.setUTCMonth(date.getUTCMonth()+({monthly:1,quarterly:3,semiannual:6,annual:12}[bill.frequency]||1));return date.toISOString().slice(0,10)}

function fillCategory(item){if(!item)return;showView('budget');$('#categoryId').value=item.id;$('#categoryName').value=item.name;$('#categoryParent').value=item.parent_id||'';$('#categoryType').value=item.category_type;$('#categoryClassification').value=item.classification||'';$('#categoryName').focus()}
function fillTransaction(item){if(!item)return;showView('transactions');$('#transactionId').value=item.id;$('#transactionType').value=item.transaction_type;$('#transactionAmount').value=(item.amount_minor/100).toFixed(2);$('#transactionDescription').value=item.description;$('#transactionDate').value=item.transaction_date;$('#transactionCategory').value=item.category_id||'';$('#transactionAsset').value=item.asset_id||'';$('#transactionIncomeSource').value=item.income_source_id||'';$('#transactionNotes').value=item.notes||''}
function fillBill(item){if(!item)return;showView('bills');$('#billId').value=item.id;$('#billName').value=item.name;$('#billAmount').value=(item.amount_minor/100).toFixed(2);$('#billCategory').value=item.category_id||'';$('#billDate').value=item.next_due_date;$('#billFrequency').value=item.frequency;$('#billCustomDays').value=item.custom_interval_days||'';$('#billClassification').value=item.classification;$('#billActive').checked=item.active;$('#billNotes').value=item.notes||''}
function fillIncomeSource(item){if(!item)return;showView('earnings');$('#incomeSourceId').value=item.id;$('#incomeSourceName').value=item.name;$('#incomeSourceType').value=item.income_type;$('#incomeHourlyRate').value=item.hourly_rate_minor==null?'':(item.hourly_rate_minor/100).toFixed(2);$('#incomeExpectedHours').value=item.standard_weekly_minutes==null?'':item.standard_weekly_minutes/60;$('#incomeSalary').value=item.annual_salary_minor==null?'':(item.annual_salary_minor/100).toFixed(2);$('#incomeFrequency').value=item.pay_frequency;$('#incomeOvertime').value=item.overtime_multiplier_basis_points/10000;updateIncomeSourceExperience();$('#incomeSourceName').focus()}
function fillPaycheck(item){if(!item)return;showView('earnings');$('#paycheckId').value=item.id;$('#paycheckSource').value=item.income_source_id;$('#payPeriodStart').value=item.period_start;$('#payPeriodEnd').value=item.period_end;$('#payDate').value=item.pay_date;$('#payGross').value=(item.estimated_gross_minor/100).toFixed(2);$('#payPreTax').value=(item.estimated_pre_tax_minor/100).toFixed(2);$('#payRetirement').value=(item.estimated_retirement_minor/100).toFixed(2);$('#payBenefits').value=(item.estimated_benefits_minor/100).toFixed(2);$('#payPostTax').value=(item.estimated_post_tax_minor/100).toFixed(2);const fields={actualGross:'actual_gross_minor',actualNet:'actual_net_minor',actualFederal:'actual_federal_minor',actualState:'actual_state_minor',actualSocialSecurity:'actual_social_security_minor',actualMedicare:'actual_medicare_minor',actualRetirement:'actual_retirement_minor',actualEmployerRetirement:'employer_retirement_minor',actualBenefits:'actual_benefits_minor',actualOther:'actual_other_deductions_minor'};Object.entries(fields).forEach(([id,key])=>$(`#${id}`).value=item[key]==null?'':(item[key]/100).toFixed(2));updatePayEstimate()}
function fillSavings(item){if(!item)return;$('#savingsId').value=item.id;$('#savingsName').value=item.name;$('#savingsCurrent').value=(item.current_minor/100).toFixed(2);$('#savingsTarget').value=(item.target_minor/100).toFixed(2);$('#savingsMonthly').value=(item.monthly_contribution_minor/100).toFixed(2);$('#savingsDate').value=item.target_date||'';$('#savingsNotes').value=item.notes||''}
function fillAsset(item){if(!item)return;$('#assetId').value=item.id;$('#assetName').value=item.name;$('#assetGroup').value=item.asset_group;$('#assetType').value=item.asset_type;$('#assetValue').value=(item.current_value_minor/100).toFixed(2);$('#assetPurchaseDate').value=item.purchase_date||'';$('#assetPurchasePrice').value=item.purchase_price_minor==null?'':(item.purchase_price_minor/100).toFixed(2);$('#assetNotes').value=item.notes||''}
function fillRetirementForm(item,force=true){if(!force&&$('#retirementForm').dataset.loaded===item.id)return;$('#retirementForm').dataset.loaded=item.id;$('#retCurrentAge').value=item.current_age;$('#retirementAge').value=item.retirement_age;$('#retIncome').value=(item.annual_income_minor/100).toFixed(2);$('#retContribution').value=item.employee_contribution_basis_points/100;$('#retMatch').value=item.employer_match_basis_points/100;$('#retMatchLimit').value=item.employer_match_limit_basis_points/100;$('#retAdditional').value=(item.additional_annual_minor/100).toFixed(2);$('#retReturn').value=item.expected_return_basis_points/100;$('#retInflation').value=(item.inflation_basis_points||0)/100}

function currentPayEstimate(){return paycheckEstimate({grossMinor:parseZero($('#payGross').value),preTaxMinor:parseZero($('#payPreTax').value),retirementMinor:parseZero($('#payRetirement').value),benefitsMinor:parseZero($('#payBenefits').value),federalBasisPoints:Math.round(Number($('#payFederalRate').value||0)*100),stateBasisPoints:Math.round(Number($('#payStateRate').value||0)*100),postTaxMinor:parseZero($('#payPostTax').value)})}
function updatePayEstimate(){try{const value=currentPayEstimate();$('#payEstimate').textContent=`Estimated take-home: ${formatMoney(value.netMinor)} · deductions ${formatMoney(value.deductionsMinor)}`}catch{$('#payEstimate').textContent='Estimated take-home: —'}}
function updateWorkEstimate(){const source=state.incomeSources.find(x=>x.id===$('#workSource').value);if(!source||source.hourly_rate_minor==null)return $('#workEstimate').textContent='Choose an hourly source.';const regular=Math.round(Number($('#workRegular').value||0)*60),overtime=Math.round(Number($('#workOvertime').value||0)*60);$('#workEstimate').textContent=`Estimated gross: ${formatMoney(hourlyGross(source.hourly_rate_minor,regular,overtime,source.overtime_multiplier_basis_points))}`}
function sourceExpectedMonthly(item){if(item.hourly_rate_minor!=null&&item.standard_weekly_minutes)return Math.round(Number(item.hourly_rate_minor)*Number(item.standard_weekly_minutes)*52/60/12);if(item.annual_salary_minor!=null)return Math.round(Number(item.annual_salary_minor)/12);return 0}
function sourceExpectedPaycheck(item){const annual=item.hourly_rate_minor!=null&&item.standard_weekly_minutes?Math.round(Number(item.hourly_rate_minor)*Number(item.standard_weekly_minutes)*52/60):Number(item.annual_salary_minor||0),periods={weekly:52,biweekly:26,semimonthly:24,monthly:12,quarterly:4,annual:1}[item.pay_frequency];return periods?Math.round(annual/periods):0}
function expectedMonthlyIncome(){return state.incomeSources.filter(x=>x.active).reduce((total,item)=>total+sourceExpectedMonthly(item),0)}
function updateIncomeSourceExperience(){const type=$('#incomeSourceType').value,isHourly=type==='hourly';$$('[data-income-field="hourly"],[data-income-field="hours"],[data-income-field="overtime"]').forEach(x=>x.hidden=!isHourly);$$('[data-income-field="annual"]').forEach(x=>x.hidden=isHourly);try{if(isHourly){const rate=parseZero($('#incomeHourlyRate').value),minutes=Math.round(Number($('#incomeExpectedHours').value||0)*60);$('#incomeSourcePreview').innerHTML=rate&&minutes?`<strong>${formatMoney(rate)} / hour</strong><span>≈ ${formatMoney(Math.round(rate*minutes/60))} / week · ≈ ${formatMoney(Math.round(rate*minutes*52/60/12))} / month before deductions</span>`:`<strong>${rate?`${formatMoney(rate)} / hour`:'Add your hourly rate'}</strong><span>Add expected hours or track worked hours to estimate income.</span>`}else{const annual=parseZero($('#incomeSalary').value),frequency=$('#incomeFrequency').value,periods={weekly:52,biweekly:26,semimonthly:24,monthly:12}[frequency];$('#incomeSourcePreview').innerHTML=annual?`<strong>${formatMoney(annual)} / year</strong><span>≈ ${formatMoney(Math.round(annual/12))} / month${periods?` · ≈ ${formatMoney(Math.round(annual/periods))} per paycheck`:''} before deductions</span>`:'Enter an annual amount to see a simple estimate.'}}catch{$('#incomeSourcePreview').textContent='Use a valid positive amount to see an estimate.'}}
function enhanceRetirementDisclosure(){const retirement=$('[data-view="retirement"]'),splits=$$('.split-layout',retirement),form=$('#retirementForm');if(form&&!form.closest('.feature-disclosure')){const details=document.createElement('details');details.className='feature-disclosure retirement-controls';details.innerHTML='<summary><span><b>Explore projection assumptions</b><small>Age, contributions, match, and expected return</small></span><i>Open</i></summary>';form.before(details);details.append(form)}const accountTools=splits[1]?.firstElementChild;if(accountTools&&!accountTools.closest('.feature-disclosure')){const details=document.createElement('details');details.className='feature-disclosure retirement-controls';details.innerHTML='<summary><span><b>Accounts & allocation</b><small>Add accounts and track current versus target allocation</small></span><i>Open</i></summary>';accountTools.before(details);details.append(accountTools)}}
function retirementInput(){return{currentAge:Number($('#retCurrentAge').value||30),retirementAge:Number($('#retirementAge').value||67),annualIncomeMinor:parseZero($('#retIncome').value),currentBalanceMinor:sum(state.retirementAccounts,'current_balance_minor'),employeeBasisPoints:Math.round(Number($('#retContribution').value||0)*100),matchBasisPoints:Math.round(Number($('#retMatch').value||0)*100),matchLimitBasisPoints:Math.round(Number($('#retMatchLimit').value||0)*100),additionalAnnualMinor:parseZero($('#retAdditional').value),returnBasisPoints:Math.round(Number($('#retReturn').value||0)*100)}}
function applyRetirementScenario(value){if(value!=='custom')$('#retContribution').value=Number(value)/100;renderRetirement()}

function loadSettings(){try{const saved=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return{theme:THEMES.includes(saved.theme)?saved.theme:'classic',density:saved.density==='compact'?'compact':'comfortable',onboardingDismissed:saved.onboardingDismissed===true}}catch{return{...DEFAULT_SETTINGS}}}
function applySettings(){document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.density=settings.density;const colors={classic:'#183b35',ledger:'#493c2d',clear:'#183b4d',vault:'#050f0c',market:'#050607'};$('#themeColor').content=colors[settings.theme]}
function persistSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
function openSettings(){showSettingsPanel('main',false);$('#settingsEmail').textContent=currentUser?.email||'Signed-in account';$$('input[name="money-theme"]').forEach(x=>x.checked=x.value===settings.theme);$$('input[name="money-density"]').forEach(x=>x.checked=x.value===settings.density);$('#settingsModal').showModal();setTimeout(()=>$('[data-settings-open]',$('#settingsModal'))?.focus(),0)}
function showSettingsPanel(name,focus=true){$$('[data-settings-panel]',$('#settingsModal')).forEach(x=>x.classList.toggle('active',x.dataset.settingsPanel===name));if(focus)setTimeout(()=>(name==='main'?$('[data-settings-open]',$('#settingsModal')):$('[data-settings-back]',$('#settingsModal')))?.focus(),0)}
function saveSettingsControls(){settings={...settings,theme:$('input[name="money-theme"]:checked')?.value||settings.theme,density:$('input[name="money-density"]:checked')?.value||settings.density};persistSettings();applySettings()}
function settingsModalClose(){if($('#settingsModal').open)$('#settingsModal').close()}
function runQuickAction(action){const destinations={income:'transactions',expense:'transactions',bill:'bills',savings:'savings'};showView(destinations[action]);if(action==='income'||action==='expense'){$('#transactionType').value=action;$('#transactionAmount').focus()}else if(action==='bill')$('#billName').focus();else $('#savingsName').focus()}
function hasMeaningfulMoneyData(){return ['budgets','assets','incomeSources','workEntries','paychecks','transactions','bills','savingsGoals','contributions','retirementProfiles','retirementAccounts','allocations','snapshots'].some(key=>state[key].length>0)}
function maybeOpenOnboarding(){if(settings.onboardingDismissed||hasMeaningfulMoneyData())return;setTimeout(()=>{if(!$('#onboardingModal').open){showOnboardingStep(1);$('#onboardingModal').showModal()}},350)}
function showOnboardingStep(step){onboardingStep=Math.max(1,Math.min(4,step));$$('[data-onboarding-step]').forEach(x=>x.classList.toggle('active',Number(x.dataset.onboardingStep)===onboardingStep));$('#onboardingStepLabel').textContent=`Step ${onboardingStep} of 4`;$('.onboarding-progress i').style.width=`${onboardingStep*25}%`;$('#onboardingBack').hidden=onboardingStep===1;$('#onboardingNext').textContent=onboardingStep===4?'Finish setup':'Continue'}
function onboardingType(){return $('input[name="onboarding-income-type"]:checked')?.value||'salary'}
function updateOnboardingFields(){const type=onboardingType(),hourly=type==='hourly';$('#onboardingAmountLabel').childNodes[0].nodeValue=hourly?'Hourly rate':'Annual amount';$('#onboardingHoursField').hidden=!hourly;updateOnboardingPreview()}
function updateOnboardingPreview(){try{const amount=parseZero($('#onboardingIncomeAmount').value),type=onboardingType(),hours=Number($('#onboardingHours').value||0);if(!amount)return $('#onboardingPreview').textContent='Add an amount to preview your expected income.';if(type==='hourly')$('#onboardingPreview').innerHTML=hours?`<strong>${formatMoney(amount)} / hour</strong><span>≈ ${formatMoney(Math.round(amount*hours))} / week · ≈ ${formatMoney(Math.round(amount*hours*52/12))} / month</span>`:`<strong>${formatMoney(amount)} / hour</strong><span>Add expected hours later or track the hours you actually work.</span>`;else $('#onboardingPreview').innerHTML=`<strong>${formatMoney(amount)} / year</strong><span>≈ ${formatMoney(Math.round(amount/12))} / month before deductions</span>`}catch{$('#onboardingPreview').textContent='Enter a valid amount to continue.'}}
async function advanceOnboarding(){if(onboardingStep<4)return showOnboardingStep(onboardingStep+1);$('#onboardingNext').disabled=true;try{const type=onboardingType(),amount=optionalMoney($('#onboardingIncomeAmount').value),name=$('#onboardingIncomeName').value.trim(),frequency=$('input[name="onboarding-frequency"]:checked')?.value||'biweekly',hours=Number($('#onboardingHours').value||0);if(name&&amount){await saveRow('incomeSources',{id:crypto.randomUUID(),name,income_type:type,hourly_rate_minor:type==='hourly'?amount:null,annual_salary_minor:type==='hourly'?null:amount,pay_frequency:frequency,standard_weekly_minutes:type==='hourly'&&hours?Math.round(hours*60):null,overtime_multiplier_basis_points:15000,notes:'',active:true})}for(const input of $$('[data-starter-bill]')){const billAmount=optionalMoney(input.value);if(!billAmount)continue;const name=input.dataset.starterBill,category=state.categories.find(x=>x.category_type==='expense'&&(x.name===name||name.toLowerCase().includes(x.name.toLowerCase())||x.name.toLowerCase().includes(name.split(' ')[0].toLowerCase())));await saveRow('bills',{id:crypto.randomUUID(),name,amount_minor:billAmount,category_id:category?.id||null,next_due_date:today(),frequency:'monthly',custom_interval_days:null,classification:'fixed',notes:'Added during setup',active:true,last_materialized_due_date:null})}settings.onboardingDismissed=true;persistSettings();$('#onboardingModal').close();populateControls();renderAll()}catch{alert('Setup could not be saved. Check the amounts or skip and add these items later.')}finally{$('#onboardingNext').disabled=false}}
function dismissOnboarding(){settings.onboardingDismissed=true;persistSettings();$('#onboardingModal').close()}
async function resetMoney(){if(!confirm('Permanently delete every Money record in this account? This cannot be undone.'))return;if(prompt('Type RESET MONEY to confirm')!=='RESET MONEY')return;const order=['contributions','transactions','workEntries','paychecks','budgets','bills','allocations','retirementAccounts','retirementProfiles','snapshots','savingsGoals','assets','incomeSources','categories'];try{for(const key of order){const{error}=await client.from(TABLES[key]).delete().eq('user_id',currentUser.id);if(error)throw error}state=Object.fromEntries(Object.keys(TABLES).map(key=>[key,[]]));await seedCategories();settingsModalClose();populateControls();renderAll()}catch{alert('Money data could not be reset. No further deletes were attempted after the failure.')}}

function reportBounds(range){const end=today();if(range==='custom')return{start:$('#reportStart').value||end,end:$('#reportEnd').value||end};const now=new Date(`${end}T00:00:00Z`),start=new Date(now);if(range==='month')start.setUTCDate(1);if(range==='3m')start.setUTCMonth(start.getUTCMonth()-3);if(range==='6m')start.setUTCMonth(start.getUTCMonth()-6);if(range==='1y')start.setUTCFullYear(start.getUTCFullYear()-1);if(range==='ytd')start.setUTCMonth(0,1);return{start:start.toISOString().slice(0,10),end}}
function monthlyBillAmount(item){const amount=Number(item.amount_minor);return Math.round(amount*({weekly:52/12,biweekly:26/12,monthly:1,quarterly:1/3,semiannual:1/6,annual:1/12,custom:30/Number(item.custom_interval_days||30)}[item.frequency]||1))}
function setDefaultDates(){const date=today(),month=monthKey();['transactionDate','billDate','workDate','payDate','contributionDate','reportStart','reportEnd'].forEach(id=>{if($(`#${id}`)&&!$(`#${id}`).value)$(`#${id}`).value=date});if(!$('#payPeriodStart').value)$('#payPeriodStart').value=date;if(!$('#payPeriodEnd').value)$('#payPeriodEnd').value=date;if(!$('#overviewMonth').value)$('#overviewMonth').value=month;if(!$('#budgetMonth').value)$('#budgetMonth').value=month}
function sourceName(id){return state.incomeSources.find(x=>x.id===id)?.name||'Income source'}
function humanFrequency(value){return({weekly:'Weekly',biweekly:'Every two weeks',semimonthly:'Twice monthly',monthly:'Monthly',quarterly:'Quarterly',semiannual:'Twice a year',annual:'Annual',irregular:'Flexible',custom:'Custom'}[value]||value)}
function categoryIcon(name){const value=name.toLowerCase();if(/home|housing|rent|mortgage/.test(value))return'⌂';if(/food|grocery|restaurant|coffee/.test(value))return'◉';if(/transport|gas|car|parking/.test(value))return'↗';if(/bill|utilit|subscription/.test(value))return'◷';if(/health|medical/.test(value))return'✚';if(/saving/.test(value))return'◇';if(/entertain/.test(value))return'▷';if(/shop/.test(value))return'□';return'•'}
function parsePositive(value){const amount=parseMoney(value);if(amount<=0)throw TypeError();return amount}function parseZero(value){if(String(value??'').trim()==='')return 0;const amount=parseMoney(value);if(amount<0)throw TypeError();return amount}function optionalMoney(value){return String(value??'').trim()===''?null:parseZero(value)}
function sum(items,key){return items.reduce((total,item)=>total+Number(item[key]||0),0)}function sortOrder(a,b){return a.sort_order-b.sort_order||a.name.localeCompare(b.name)}function today(){return new Date().toISOString().slice(0,10)}
function formatHours(minutes){const value=Number(minutes||0)/60;return`${Math.round(value*100)/100} hour${value===1?'':'s'}`}
function statCard(label,value,detail,highlight=false){return`<article class="stat-card${highlight?' highlight':''}"><span>${escapeHtml(label)}</span><strong>${formatMoney(value)}</strong><small>${escapeHtml(detail)}</small></article>`}
function simpleRow(title,detail,value){return`<div class="list-row"><div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(detail)}</p></div><strong>${escapeHtml(value)}</strong></div>`}
function empty(message){return`<div class="empty">${escapeHtml(message)}</div>`}
function friendlyEmpty(title,message,actionLabel,view){return`<div class="empty friendly-empty"><span aria-hidden="true">◇</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(message)}</p><button class="button secondary" data-go-to="${view}">${escapeHtml(actionLabel)}</button></div>`}
function bar(label,value,max){return`<div class="bar-column" title="${escapeHtml(label)}: ${formatMoney(value)}"><i style="height:${Math.max(3,Math.round(value/max*150))}px"></i><span>${escapeHtml(label)}</span></div>`}
function lineChart(values){if(!values.length)return empty('No projection data.');const width=600,height=180,pad=10,max=Math.max(1,...values),min=Math.min(0,...values),span=Math.max(1,max-min),points=values.map((value,index)=>`${pad+index*(width-pad*2)/Math.max(1,values.length-1)},${height-pad-(value-min)/span*(height-pad*2)}`).join(' ');return`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Projection chart"><line class="grid" x1="${pad}" y1="${height-pad}" x2="${width-pad}" y2="${height-pad}"></line><polyline points="${points}"></polyline></svg>`}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function setCloud(message,error=false){$('#cloudStatus').textContent=message;$('#cloudStatus').classList.toggle('error',error)}
function isSchemaError(error){const code=String(error?.code||'');const message=String(error?.message||'');return ['42P01','42703','PGRST204','PGRST205'].includes(code)||/relation .* does not exist|column .* does not exist|schema cache/i.test(message)}
function showLoadError(error){const schema=isSchemaError(error);console.error('Money cloud load failed.',{code:error?.code||'unknown',kind:schema?'schema':'connection'});$('#loadNoticeText').textContent=schema?'Money needs its database migration before private records can load.':'Money could not reach your private cloud records. Your data was not changed.';$('#loadNotice').hidden=false}
function hideLoadNotice(){$('#loadNotice').hidden=true}
